const translations={
  en:{'nav.about':'About','nav.index':'Index','nav.work':'Work','nav.contact':'Contact','hero.eyebrow':'Calligraphy / Art direction','hero.manifesto':'I draw silence into motion.','hero.cta':'Enter the archive','hero.caption':'studio signal / 2026','about.eyebrow':'About the practice','about.title':'The hand is a<br /><em>thinking instrument.</em>','about.body':'Raven Hsieh is an independent calligraphy artist working between the discipline of the written line and the freedom of the moving body. Her practice turns language into atmosphere: intimate, tactile, and slightly off-centre.','about.cta':'More about Raven','index.title':'A living<br /><em>index.</em>','index.body':'A loose taxonomy of marks, commissions, and things still becoming.','index.one':'The work','index.two':'Collaborations','index.three':'Letters from the studio','work.title':'Marks with<br /><em>memory.</em>','services.title':'Made to leave<br /><em>a trace.</em>','services.body':'For people who want language to feel like a material. Available for selected commissions, cultural projects, and editorial worlds.','services.cta':'Start a conversation <span>↗</span>'},
  zh:{'nav.about':'关于','nav.index':'目录','nav.work':'作品','nav.contact':'联系','hero.eyebrow':'书法 / 艺术指导','hero.manifesto':'我把寂静画成流动。','hero.cta':'进入作品档案','hero.caption':'工作室信号 / 2026','about.eyebrow':'关于创作','about.title':'手，是一件<br /><em>思考的乐器。</em>','about.body':'Raven Hsieh 是一位独立书法艺术家，在书写的秩序与身体的自由之间工作。她把语言变成一种氛围：亲密、触感鲜明，又略微偏离中心。','about.cta':'更多关于 Raven','index.title':'一份正在生长的<br /><em>目录。</em>','index.body':'关于笔触、委托，以及仍在成为的事物。','index.one':'作品','index.two':'合作','index.three':'来自工作室的信','work.title':'带着<br /><em>记忆的笔迹。</em>','services.title':'留下<br /><em>一点痕迹。</em>','services.body':'为希望语言拥有材质感的人而作。接受精选委托、文化项目与编辑类创作。','services.cta':'开始交流 <span>↗</span>'},
  ja:{'nav.about':'紹介','nav.index':'目次','nav.work':'作品','nav.contact':'連絡','hero.eyebrow':'書 / アートディレクション','hero.manifesto':'静けさを、動きに描く。','hero.cta':'アーカイブへ','hero.caption':'studio signal / 2026','about.eyebrow':'創作について','about.title':'手は、<br /><em>考える楽器。</em>','about.body':'Raven Hsieh は、書かれた線の規律と動く身体の自由の間で活動する独立書家です。言葉を空気へ変える。親密で、触覚的で、少し中心からずれたものへ。','about.cta':'Raven について','index.title':'生きている<br /><em>目次。</em>','index.body':'線、依頼、そしてまだ形になっていないもののための分類。','index.one':'作品','index.two':'コラボレーション','index.three':'スタジオからの手紙','work.title':'記憶を宿す<br /><em>線。</em>','services.title':'痕跡を<br /><em>残すために。</em>','services.body':'言葉を素材として感じたい人へ。選ばれた依頼、文化プロジェクト、エディトリアルの世界のために。','services.cta':'話をはじめる <span>↗</span>'}
};
document.querySelectorAll('.language').forEach(btn=>btn.addEventListener('click',()=>{const lang=btn.dataset.lang;document.documentElement.lang=lang==='zh'?'zh-CN':lang;document.querySelectorAll('.language').forEach(b=>b.classList.toggle('active',b===btn));document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(translations[lang][key])el.innerHTML=translations[lang][key]})}));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const panels=[...document.querySelectorAll('main > section, footer')];panels.forEach(panel=>panel.classList.add('scroll-panel'));const panelObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting&&entry.intersectionRatio>.24){panels.forEach(panel=>panel.classList.toggle('is-current',panel===entry.target));const rail=document.querySelector('.scroll-rail i');if(rail)rail.style.transform=`translateY(${Math.max(0,panels.indexOf(entry.target)/(panels.length-1)*72)}px)`}}),{threshold:[.24,.48,.7]});panels.forEach(panel=>panelObserver.observe(panel));
const transitionTypes=['curtain','orb','lift','line','split','soft'];panels.forEach((panel,index)=>panel.dataset.transition=transitionTypes[index%transitionTypes.length]);
document.querySelectorAll('.tilt').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5,amount=Number(el.dataset.tilt||8);el.style.transform=`perspective(900px) rotateX(${y*-amount}deg) rotateY(${x*amount}deg) scale(1.015)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{const filter=btn.dataset.filter;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b===btn));document.querySelectorAll('.work-item').forEach(item=>{item.style.display=filter==='all'||item.dataset.category===filter?'block':'none'})}));
document.querySelectorAll('.magnetic-button').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.12}px, ${(e.clientY-r.top-r.height/2)*.12}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});

// Page entrance, section wipe, and custom feather cursor.
const cursor=document.querySelector('.quill-cursor');
const motionOK=!window.matchMedia('(prefers-reduced-motion: reduce)').matches;
if(motionOK&&cursor){document.body.classList.add('custom-cursor');let mx=0,my=0,cx=0,cy=0;window.addEventListener('pointermove',event=>{mx=event.clientX;my=event.clientY;cursor.classList.add('is-visible')},{passive:true});const follow=()=>{cx+=(mx-cx)*.18;cy+=(my-cy)*.18;cursor.style.left=`${cx}px`;cursor.style.top=`${cy}px`;requestAnimationFrame(follow)};follow();document.querySelectorAll('.artwork-zone,.work-item,.hero-art').forEach(zone=>{zone.addEventListener('pointerenter',()=>cursor.classList.add('is-hovering'));zone.addEventListener('pointerleave',()=>cursor.classList.remove('is-hovering'));zone.addEventListener('pointerdown',event=>{const burst=document.createElement('i');burst.className='ink-burst';burst.style.left=`${event.clientX-5}px`;burst.style.top=`${event.clientY-5}px`;document.body.appendChild(burst);setTimeout(()=>burst.remove(),750)})})}
if(motionOK&&cursor){let lastFeather=0;const languageControls=document.querySelector('.language-switcher');languageControls.addEventListener('pointerenter',()=>cursor.classList.add('is-hidden'));languageControls.addEventListener('pointerleave',()=>cursor.classList.remove('is-hidden'));window.addEventListener('pointermove',event=>{if(event.target.closest('.language-switcher'))return;const now=Date.now();if(now-lastFeather<520)return;lastFeather=now;const feather=document.createElement('span');feather.className='feather-drift';feather.style.left=`${event.clientX-10}px`;feather.style.top=`${event.clientY-4}px`;feather.style.setProperty('--drift-x',`${Math.round((Math.random()-.5)*70)}px`);feather.innerHTML='<img src="assets/quill-cursor.png" alt="" />';document.body.appendChild(feather);setTimeout(()=>feather.remove(),1900)},{passive:true})}
if(motionOK&&cursor){let featherX=innerWidth*.5,featherY=innerHeight*.4;window.addEventListener('pointermove',event=>{featherX=event.clientX;featherY=event.clientY},{passive:true});const dropFeather=()=>{const feather=document.createElement('span');feather.className='feather-drift';feather.style.left=`${featherX-10+Math.round((Math.random()-.5)*34)}px`;feather.style.top=`${featherY-4+Math.round((Math.random()-.5)*18)}px`;feather.style.setProperty('--drift-x',`${Math.round((Math.random()-.5)*110)}px`);feather.innerHTML='<img src="assets/quill-cursor.png" alt="" />';document.body.appendChild(feather);setTimeout(()=>feather.remove(),1900)};setInterval(dropFeather,260)}
const wipe=document.querySelector('.page-transition');document.querySelectorAll('a[href^="#"]').forEach(link=>link.addEventListener('click',event=>{const target=document.querySelector(link.getAttribute('href'));if(!target||!motionOK)return;event.preventDefault();wipe.classList.remove('active');void wipe.offsetWidth;wipe.classList.add('active');setTimeout(()=>target.scrollIntoView({behavior:'smooth',block:'start'}),470)}));

const projectData={herself:'herself',ritual:'ritual',slow:'slow',water:'water',becoming:'becoming'};
const details={ritual:{number:'01',type:'Identity / 2025',title:'Ritual <em>No. 01</em>',summary:'A study in the quiet tension between ceremony and the everyday mark.',brief:'A visual identity for a culture of slow attention.',gesture:'The final mark keeps the hand visible: imperfect, deliberate, alive.',word:'ritual',detail:'the line returns',tone:'ritual-tone'},slow:{number:'02',type:'Editorial / 2024',title:'Slow <em>Is A Shape</em>',summary:'Letterforms for a publication that treats time as a material.',brief:'An editorial system built around pause, breath, and generous white space.',gesture:'The lettering stretches until the words begin to feel like objects.',word:'slow',detail:'a slower kind of loud',tone:'slow-tone'},water:{number:'03',type:'Identity / 2024',title:'As <em>Water</em>',summary:'A fluid identity for a studio moving between language and landscape.',brief:'A mark that could hold both a quiet pool and a sudden current.',gesture:'The brush leaves room for the eye to complete the movement.',word:'water',detail:'let it move',tone:'water-tone'},becoming:{number:'04',type:'Editorial / 2023',title:'Still <em>Becoming</em>',summary:'A lettering essay on the unfinished, the almost, and the in-between.',brief:'A visual language for a journal interested in process over polish.',gesture:'The unfinished edge is not corrected. It is the point.',word:'becoming',detail:'not yet / not never',tone:'becoming-tone'}};
if(document.body.classList.contains('project-page')){const key=new URLSearchParams(location.search).get('project')||'ritual';const data=details[key]||details.ritual;Object.entries({ 'project-number':data.number,'project-type':data.type,'project-title':data.title,'project-summary':data.summary,'project-brief':data.brief,'project-gesture':data.gesture,'gallery-word':data.word,'gallery-detail':data.detail}).forEach(([id,value])=>{const el=document.getElementById(id);if(el)el.innerHTML=value});document.getElementById('project-art')?.classList.add(data.tone);document.getElementById('gallery-large')?.classList.add(data.tone)}
const typeText=element=>{const value=element.textContent.trim();element.innerHTML=[...value].map((char,index)=>`<span class="type-char" style="animation-delay:${index*.035}s">${char===' '?'&nbsp;':char}</span>`).join('')};document.querySelectorAll('.typing-copy').forEach(typeText);
const directionMemory=new WeakMap();const directionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{const previous=directionMemory.get(entry.target)??entry.boundingClientRect.top;const goingUp=entry.boundingClientRect.top>previous;directionMemory.set(entry.target,entry.boundingClientRect.top);if(entry.isIntersecting&&entry.intersectionRatio>.3){entry.target.classList.toggle('is-reversing',goingUp);entry.target.querySelectorAll('.kinetic-title').forEach(title=>{title.style.animation='none';void title.offsetWidth;title.style.animation='';});entry.target.querySelectorAll('.typing-copy').forEach(copy=>{copy.querySelectorAll('.type-char').forEach((char,index)=>{char.style.animationDelay=goingUp?`${(copy.children.length-index)*.018}s`:`${index*.035}s`;});})}}),{threshold:[.3,.55,.8]});panels.forEach(panel=>directionObserver.observe(panel));
const routeSlide=document.querySelector('.t-page-slide');
const modalProjects={herself:{title:'The Birth <em>of Herself</em>',meta:'Personal work / 2026.7 / iPad Procreate',lede:'A little mess of lines, stars, and the moment a woman gives herself permission to begin again.',image:'assets/the-birth-of-herself.jpg',alt:'The Birth of Herself, an ink drawing by Raven Hsieh',medium:'iPad Procreate',year:'2026.7',kind:'Personal work',story:["I started with a very tidy plan: make the words orbit in a ring, then add some stars. ‘daughter of earth, child of the stars’ was supposed to sit somewhere in there too. Very composed. Very under control. ✨","Then I kept drawing. More lines arrived, the words got rubbed out, and the circle quietly gave up on being a circle. Honestly, good for her.","What stayed is a woman becoming visible to herself. Not perfectly, not all at once, but with a kind of stubborn tenderness. This is about feminism, self-rebirth, and the small fierce feeling of coming home to your own name. 🤍"]},ritual:{title:'Ritual <em>No. 01</em>',meta:'Identity / 2025',lede:'A study in the quiet tension between ceremony and the everyday mark.',image:'assets/studio-signal.png',alt:'Ritual No. 01 project study',medium:'Digital lettering',year:'2025',kind:'Identity commission',story:['A mark built to feel intentional without becoming stiff.','The structure holds, then the gesture interrupts it. That slight imbalance is where the pulse lives.']},slow:{title:'Slow <em>Is A Shape</em>',meta:'Editorial / 2024',lede:'Letterforms for a publication that treats time as a material.',image:'assets/studio-signal.png',alt:'Slow Is A Shape project study',medium:'Digital lettering',year:'2024',kind:'Editorial work',story:['A lettering system that lets the eye rest before it continues.','The forms stretch a little longer than expected, because the pause is part of the sentence.']},water:{title:'As <em>Water</em>',meta:'Identity / 2024',lede:'A fluid identity for a studio moving between language and landscape.',image:'assets/studio-signal.png',alt:'As Water project study',medium:'Digital lettering',year:'2024',kind:'Identity commission',story:['The line moves softly, then changes direction when it needs to.','A reminder that a mark can carry both a current and a place to be still.']},becoming:{title:'Still <em>Becoming</em>',meta:'Editorial / 2023',lede:'A lettering essay on the unfinished, the almost, and the in-between.',image:'assets/studio-signal.png',alt:'Still Becoming project study',medium:'Digital lettering',year:'2023',kind:'Editorial work',story:['This piece stays with the unfinished edge instead of correcting it.','Not everything needs to resolve before it can be worth looking at.']}};
const modal=document.querySelector('.project-modal');const closeModal=()=>{if(!modal)return;modal.classList.remove('is-open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');if(new URLSearchParams(location.search).has('project'))history.replaceState({},'',`${location.pathname}${location.hash}`);};const openModal=key=>{const data=modalProjects[key];if(!modal||!data)return;document.getElementById('modal-title').innerHTML=data.title;document.getElementById('modal-meta').textContent=data.meta;document.getElementById('modal-lede').textContent=data.lede;const image=document.getElementById('modal-image');image.src=data.image;image.alt=data.alt;document.getElementById('modal-medium').textContent=data.medium;document.getElementById('modal-year').textContent=data.year;document.getElementById('modal-kind').textContent=data.kind;document.getElementById('modal-story').innerHTML=data.story.map(paragraph=>`<p>${paragraph}</p>`).join('');modal.classList.add('is-open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');modal.querySelector('.project-modal-close').focus();};document.querySelectorAll('.work-item[data-project],.hero-art[data-project]').forEach(item=>{const show=()=>openModal(item.dataset.project);item.addEventListener('click',show);item.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();show();}})});modal?.querySelectorAll('[data-modal-close],.project-modal-close').forEach(control=>control.addEventListener('click',closeModal));window.addEventListener('keydown',event=>{if(event.key==='Escape')closeModal();});
if(document.body.classList.contains('project-page')){const project=new URLSearchParams(location.search).get('project')||'herself';location.replace(`index.html?project=${project}`)}else{const requestedProject=new URLSearchParams(location.search).get('project');if(requestedProject&&modalProjects[requestedProject])setTimeout(()=>openModal(requestedProject),180)}
document.querySelectorAll('a[href^="index.html"]').forEach(link=>link.addEventListener('click',event=>{if(!motionOK||!routeSlide)return;event.preventDefault();event.stopImmediatePropagation();routeSlide.classList.add('is-running');routeSlide.dataset.page='1';setTimeout(()=>{location.href=link.getAttribute('href')},520)},{capture:true}));
const hero=document.querySelector('.hero');if(hero&&motionOK){const heroProgress=new IntersectionObserver(entries=>entries.forEach(entry=>{const rect=entry.boundingClientRect;const progress=Math.min(1,Math.max(0,(-rect.top)/(Math.max(1,rect.height*.72))));hero.style.setProperty('--hero-progress',progress.toFixed(3))}),{threshold:Array.from({length:21},(_,i)=>i/20)});heroProgress.observe(hero)}

// Each chapter owns a single, directional text entrance: silk-like title reveal + letter-by-letter copy.
document.querySelectorAll('.services h2,.site-footer h2,.project-next strong').forEach(title=>title.classList.add('kinetic-title'));
document.querySelectorAll('.services .service-intro').forEach(copy=>copy.classList.add('typing-copy'));
const textMotionMemory=new WeakMap();let activeTextPanel=null;
const replayChapterText=(panel,reverse)=>{panel.classList.toggle('is-reversing',reverse);panel.querySelectorAll('.kinetic-title').forEach(title=>{title.style.animation='none';void title.offsetWidth;title.style.animation='';});panel.querySelectorAll('.typing-copy').forEach(copy=>{typeText(copy);[...copy.children].forEach((char,index)=>{char.style.animationDelay=reverse?`${Math.max(0,(copy.children.length-index-1)*.018)}s`:`${index*.035}s`;});});};
const chapterTextObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{const panel=entry.target;const priorTop=textMotionMemory.get(panel)??entry.boundingClientRect.top;const reverse=entry.boundingClientRect.top>priorTop;textMotionMemory.set(panel,entry.boundingClientRect.top);if(entry.isIntersecting&&entry.intersectionRatio>.48&&(activeTextPanel!==panel||panel.dataset.textDirection!==(reverse?'up':'down'))){activeTextPanel=panel;panel.dataset.textDirection=reverse?'up':'down';replayChapterText(panel,reverse)}}),{threshold:[.48,.72]});panels.forEach(panel=>chapterTextObserver.observe(panel));
document.querySelectorAll('.language').forEach(button=>button.addEventListener('click',()=>setTimeout(()=>{const activePanel=document.querySelector('.scroll-panel.is-current')||panels[0];activeTextPanel=null;replayChapterText(activePanel,false);},0)));

const stagedHero=document.querySelector('.hero');if(document.body.classList.contains('intro-staging')&&stagedHero){setTimeout(()=>{document.body.classList.remove('intro-staging');document.body.classList.add('hero-intro-ready');const name=stagedHero.querySelector('.kinetic-title');name.style.animation='none';void name.offsetWidth;name.style.animation='';stagedHero.querySelectorAll('.typing-copy .type-char').forEach((char,index)=>{char.style.animation='type-in .055s cubic-bezier(.16,1,.3,1) forwards';char.style.animationDelay=`${.92+index*.048}s`;});},2250)}

const studiesRibbon=document.querySelector('.study-marquee');const studiesTrack=studiesRibbon?.querySelector('.study-track');if(motionOK&&studiesRibbon&&studiesTrack){let ribbonOffset=0;let ribbonSpeed=-52;let ribbonTarget=-52;let ribbonFrame=0;let ribbonLast=0;const ribbonSpan=()=>studiesTrack.scrollWidth/2;const tickRibbon=time=>{if(!ribbonLast)ribbonLast=time;const delta=Math.min((time-ribbonLast)/1000,.04);ribbonLast=time;ribbonSpeed+=(ribbonTarget-ribbonSpeed)*.075;ribbonOffset+=ribbonSpeed*delta;const span=ribbonSpan();if(span){while(ribbonOffset<=-span)ribbonOffset+=span;while(ribbonOffset>0)ribbonOffset-=span;studiesTrack.style.transform=`translate3d(${ribbonOffset}px,0,0)`}ribbonFrame=requestAnimationFrame(tickRibbon)};const startRibbon=()=>{if(!ribbonFrame){ribbonLast=0;ribbonFrame=requestAnimationFrame(tickRibbon)}};const stopRibbon=()=>{if(ribbonFrame){cancelAnimationFrame(ribbonFrame);ribbonFrame=0}};studiesRibbon.addEventListener('pointermove',event=>{const bounds=studiesRibbon.getBoundingClientRect();ribbonTarget=event.clientX<bounds.left+bounds.width/2?-208:208;startRibbon()});studiesRibbon.addEventListener('pointerleave',()=>{ribbonTarget=-52;startRibbon()});new IntersectionObserver(entries=>entries.forEach(entry=>entry.isIntersecting?startRibbon():stopRibbon()),{threshold:.05}).observe(studiesRibbon);}
const verticalFlow=document.querySelector('.vertical-index-flow');const verticalTrack=verticalFlow?.querySelector('.vertical-index-track');if(motionOK&&verticalFlow&&verticalTrack){let verticalOffset=0;let verticalSpeed=-48;let verticalTarget=-48;let verticalFrame=0;let verticalLast=0;const verticalSpan=()=>verticalTrack.scrollHeight/2;const tickVertical=time=>{if(!verticalLast)verticalLast=time;const delta=Math.min((time-verticalLast)/1000,.04);verticalLast=time;verticalSpeed+=(verticalTarget-verticalSpeed)*.075;verticalOffset+=verticalSpeed*delta;const span=verticalSpan();if(span){while(verticalOffset<=-span)verticalOffset+=span;while(verticalOffset>0)verticalOffset-=span;verticalTrack.style.transform=`translate3d(0,${verticalOffset}px,0)`}verticalFrame=requestAnimationFrame(tickVertical)};const startVertical=()=>{if(!verticalFrame){verticalLast=0;verticalFrame=requestAnimationFrame(tickVertical)}};const stopVertical=()=>{if(verticalFrame){cancelAnimationFrame(verticalFrame);verticalFrame=0}};verticalFlow.addEventListener('pointermove',event=>{const bounds=verticalFlow.getBoundingClientRect();verticalTarget=event.clientY<bounds.top+bounds.height/2?-192:192;startVertical()});verticalFlow.addEventListener('pointerleave',()=>{verticalTarget=-48;startVertical()});new IntersectionObserver(entries=>entries.forEach(entry=>entry.isIntersecting?startVertical():stopVertical()),{threshold:.05}).observe(verticalFlow);}

// Keep every project detail in step with the site language switcher.
Object.assign(modalProjects.slow,{title:'Mary',meta:'Personal work / 2026.8 / iPad Procreate',lede:'A quiet study of the serenity Mary might offer the world.',image:'assets/mary-2026.jpg',alt:'Mary, an illustration and calligraphy work by Raven Hsieh',medium:'iPad Procreate',year:'2026.8',kind:'Personal work',story:['I have genuinely lost count of the revisions. I kept drawing, correcting, and then correcting the correction.','The halo alone went through four versions after a very earnest group chat with two friends. We debated it all the way down to this faintest one.','That was it: sacredness apparently arrives through restraint. Who knew the softest halo would have the most authority? ✨']});
Object.assign(modalProjects.water,{title:'Max',meta:'Personal work / 2026.6 / iPad Procreate',lede:'Can calligraphy do more than write words? This time, I let it build a person: Max.',image:'assets/max-2026.jpg',alt:'Max, a typographic portrait by Raven Hsieh',medium:'iPad Procreate',year:'2026.6',kind:'Personal work',story:['I have always thought Max carries a rare kind of strength. She gets scared, angry, avoids things, and is sometimes trapped by the past. But she is never waiting around for someone else to save her.','That Running Up That Hill moment hits because it is not only fantasy. It makes me believe that a person can keep running with their scars, still reaching for whatever little light is left. ⚡','Instead of sketching her outline, I gathered around 70 lines that felt like Max and let them slowly become her face. A character is not only drawn. She can be rebuilt from what she has said, survived, and left with us. ✍️']});
modalProjects.persephone={title:'Persephone',meta:'Personal work / 2026.7 / iPad Procreate',lede:'The girl taken into the underworld, returning with spring in her veins.',image:'assets/persephone-2026.jpg',alt:'Persephone, a calligraphy and illustration work by Raven Hsieh',medium:'iPad Procreate',year:'2026.7',kind:'Personal work',story:['They buried my name beneath the earth, thinking the darkness would silence me. But beneath the roots, I learned the language of stones, and heard the forgotten songs of the sleeping seeds.','From the kingdom of shadows, I returned with spring in my veins, wearing the night not as a wound, but as a crown. I am neither the maiden they lost, nor the queen they feared.','I am the season between death and rebirth, the woman who bloomed from her own darkness. ✦']};
Object.assign(modalProjects.becoming,{title:'Guci &amp; Songwan',meta:'Wedding commission / 2026.9 / iPad Procreate',lede:'A wedding calligraphy piece for Guci and Songwan, made for the room where their promise becomes real.',image:'assets/guci-songwan-2026.jpg',alt:'Guci and Songwan wedding calligraphy commission by Raven Hsieh',medium:'iPad Procreate',year:'2026.9',kind:'Wedding commission',story:['This one was made for Guci and Songwan, for that tender moment when a wedding space starts turning into their space.','I wanted the letters to feel like two lines meeting, looping around one another without losing their own rhythm. Soft, celebratory, and a little bit floaty, just like the pre-ceremony feeling when everyone is trying not to cry. 🥹','Created in Procreate for their wedding setting, not just for a screen. I hope it gives their day one more little place to pause and smile. 🤍']});
modalProjects.garden={title:'Garden <em>Lettering</em>',meta:'Personal work / 2026.8 / iPad Procreate',lede:'An alphabet experiment where letters and plants take a long, patient walk together.',image:'assets/garden-lettering-2026.jpg',alt:'Garden Lettering, a floral alphabet study by Raven Hsieh',medium:'iPad Procreate',year:'2026.8',kind:'Personal work',story:['This is another small chapter in my garden lettering experiments: letters and plants sharing the same line, then slowly getting tangled up in it.','This time I drew a different cast of flowers and let them wind around the alphabet at an almost unreasonable pace. No rush. The vines have their own calendar. 🌿','Made in Procreate, it is a study in letting a letter become a place where something can grow. A tiny botanical detour for the alphabet. 🌼']};
const modalProjectBase=JSON.parse(JSON.stringify(modalProjects));
const modalLocales={zh:{herself:{title:'她的<br /><em>新生</em>',meta:'私人作品 / 2026.7 / iPad Procreate',lede:'一些线、一些星星，还有一个女人允许自己重新开始的时刻。',medium:'iPad Procreate',year:'2026.7',kind:'私人作品',story:['我一开始有个特别规整的计划：让文字绕成一个环，再画一点星星。‘daughter of earth, child of the stars’ 也原本想放进去。很完整，很可控。✨','后来我越画线越多，字也被擦掉了一些，那个环悄悄不再像一个环。说实话，这样也挺好的。','最后留下的是一个女人重新看见自己的过程。不是完美地，不是一下子，而是带着一点固执的温柔。这张画想说女性主义、女性自我的重生，还有终于回到自己名字里的那种小小勇敢。🤍']},ritual:{title:'仪式<br /><em>第一号</em>',meta:'品牌识别 / 2025',lede:'关于仪式感与日常笔迹之间安静张力的一次研究。',medium:'数字字体设计',year:'2025',kind:'品牌委托',story:['这个标志想要有意图，但不必板正。','结构先站稳，再让手势轻轻打断它。那一点不平衡，才是它的呼吸。']},slow:{title:'缓慢<br /><em>是一种形状</em>',meta:'编辑项目 / 2024',lede:'为一本把时间当作材质的出版物所写的字。',medium:'数字字体设计',year:'2024',kind:'编辑作品',story:['让眼睛在继续阅读前，先有一个可以停一下的地方。','字形被拉得比预想更长，因为停顿本来就是句子的一部分。']},water:{title:'如<br /><em>水</em>',meta:'品牌识别 / 2024',lede:'为一个游走于语言与风景之间的工作室设计的流动身份。',medium:'数字字体设计',year:'2024',kind:'品牌委托',story:['线条先柔软地移动，再在需要时改变方向。','一笔也可以同时有水流和安静停泊的地方。']},becoming:{title:'仍在<br /><em>成为</em>',meta:'编辑项目 / 2023',lede:'一篇关于未完成、将要成为与之间状态的字形随笔。',medium:'数字字体设计',year:'2023',kind:'编辑作品',story:['这件作品选择留住未完成的边缘，而不是把它修正掉。','不是所有事情都要有结论，才值得被看见。']}},ja:{herself:{title:'彼女<br /><em>自身の誕生</em>',meta:'個人作品 / 2026.7 / iPad Procreate',lede:'線と星、そしてひとりの女性がもう一度始めることを自分に許す瞬間。',medium:'iPad Procreate',year:'2026.7',kind:'個人作品',story:['最初はきれいに決めていました。文字を輪にして、星も添えて、「daughter of earth, child of the stars」も入れるつもりでした。とても整っていて、ちゃんとコントロールできるはずでした。✨','でも描くほどに線は増え、文字は少し消え、輪は静かに輪ではなくなりました。正直、そのほうがよかった。','残ったのは、ひとりの女性がもう一度自分を見つける過程です。完璧ではなく、一度にでもなく、少し頑固でやさしい形で。フェミニズムと自己の再生、そして自分の名前に帰る小さな勇気についての絵です。🤍']},ritual:{title:'儀式<br /><em>No. 01</em>',meta:'アイデンティティ / 2025',lede:'儀式と日常の筆跡の間にある静かな緊張について。',medium:'デジタルレタリング',year:'2025',kind:'アイデンティティ依頼',story:['意図を感じさせながら、硬くなりすぎない印を目指しました。','構造を置いてから、手の動きが少しだけそれを崩す。その不均衡に鼓動があります。']},slow:{title:'ゆっくりは<br /><em>ひとつの形</em>',meta:'エディトリアル / 2024',lede:'時間を素材として扱う出版物のための文字。',medium:'デジタルレタリング',year:'2024',kind:'エディトリアル作品',story:['目が次へ進む前に、少し休める場所をつくりました。','間も文章の一部だから、字形は予想より少し長く伸びています。']},water:{title:'水の<br /><em>ように</em>',meta:'アイデンティティ / 2024',lede:'言葉と風景の間を行き来するスタジオのための流動的な印。',medium:'デジタルレタリング',year:'2024',kind:'アイデンティティ依頼',story:['線は柔らかく動き、必要なときにだけ向きを変えます。','ひとつの筆跡に、流れと静かな停泊の両方を入れました。']},becoming:{title:'まだ<br /><em>なりつつある</em>',meta:'エディトリアル / 2023',lede:'未完成と、その途中にいることについてのレタリングエッセイ。',medium:'デジタルレタリング',year:'2023',kind:'エディトリアル作品',story:['未完成の端を直さず、そのまま残しています。','すべてが解決しなくても、見る価値はあると思っています。']}}};
Object.assign(modalLocales.zh.slow,{title:'Mary',meta:'私人作品 / 2026.8 / iPad Procreate',lede:'一幅关于圣母带给世人宁静的安静练习。',medium:'iPad Procreate',year:'2026.8',kind:'私人作品',story:['到底改了多少次，我是真的不记得了。一边画一边修，再修刚才修过的地方。','光环在两位朋友认真参与讨论后，一共改了四个版本。最后我们选了这版最淡的。','结果就是它了：神圣果然是通过克制产生的。谁能想到最淡的光环反而最有分量呢？✨']});
Object.assign(modalLocales.ja.slow,{title:'Mary',meta:'個人作品 / 2026.8 / iPad Procreate',lede:'聖母が世界にもたらす静けさについての、小さな習作。',medium:'iPad Procreate',year:'2026.8',kind:'個人作品',story:['何回描き直したか、本当にもう覚えていません。描いて、直して、その直したところをまた直していました。','光輪だけでも、友人二人との真剣な相談の末に四つの案ができました。最後は一番淡いものを選びました。','それでよかった。神聖さはやはり、抑制から生まれるのかもしれません。一番淡い光輪がいちばん強かった。✨']});
Object.assign(modalLocales.zh.water,{title:'Max',meta:'私人作品 / 2026.6 / iPad Procreate',lede:'书法除了写字，还能不能一点一点塑造出一个人物？这一次，我选了 Max。',medium:'iPad Procreate',year:'2026.6',kind:'私人作品',story:['我一直觉得 Max 身上有一种很珍贵的力量。她会害怕、愤怒、逃避，也会被过去困住。但她从来不是那个等待别人拯救的人。','《Running Up That Hill》那一幕之所以让人难忘，可能不是因为它有多奇幻，而是它让人相信：带着伤痕，也依然可以继续跑，继续去抓住生活里一点点微弱的光。⚡','这次我没有只用线条勾轮廓，而是选了大约 70 句很 Max 的 vibe lines，让文字一点点组成她的样子。人物不是单纯被画出来的，也会被她说过的话、经历过的事和留给观众的力量重新塑造。✍️']});
Object.assign(modalLocales.ja.water,{title:'Max',meta:'個人作品 / 2026.6 / iPad Procreate',lede:'カリグラフィーは文字を書く以外に、ひとりの人物を形づくれるだろうか。今回は Max を選びました。',medium:'iPad Procreate',year:'2026.6',kind:'個人作品',story:['Max には、とても大切な強さがあるとずっと思っています。怖がり、怒り、逃げ、過去に閉じ込められることもある。でも誰かに救われるのを待つ人ではありません。','Running Up That Hill の場面が胸に残るのは、ファンタジーだからだけではないはず。傷を抱えたままでも走り続け、小さな光をつかみに行けると信じさせてくれるからです。⚡','今回は輪郭を線でなぞる代わりに、Max らしいと感じる約70の言葉を選び、少しずつ彼女の顔をつくりました。人物は描かれるだけでなく、彼女が語った言葉や経験、観客に残した力によっても、もう一度形づくられるのだと思います。✍️']});
modalLocales.zh.persephone={title:'Persephone',meta:'私人作品 / 2026.7 / iPad Procreate',lede:'被带入冥界的少女，带着春天重新归来。',medium:'iPad Procreate',year:'2026.7',kind:'私人作品',story:['他们把我的名字埋进地下，以为黑暗会让我沉默。但在根系之下，我学会了石头的语言，也听见了沉睡种子被遗忘的歌。','我从阴影的国度归来，血脉里带着春天，把黑夜穿在身上，不把它当作伤口，而当作王冠。我既不是他们失去的少女，也不是他们畏惧的女王。','我是死亡与重生之间的季节，是从自己的黑暗里开出花来的女人。✦']};
modalLocales.ja.persephone={title:'Persephone',meta:'個人作品 / 2026.7 / iPad Procreate',lede:'冥界へ連れ去られた少女が、血の中に春を宿して帰ってくる。',medium:'iPad Procreate',year:'2026.7',kind:'個人作品',story:['彼らは闇が私を黙らせると思い、私の名前を土の下に埋めました。でも根の下で、私は石の言葉を学び、眠る種たちの忘れられた歌を聞きました。','影の王国から、私は血の中に春を宿して帰ってきました。夜を傷ではなく冠として身につけながら。私は彼らが失った乙女でも、恐れた女王でもありません。','私は死と再生のあいだにある季節。自分自身の闇から花開いた女です。✦']};
Object.assign(modalLocales.zh.becoming,{title:'Guci &amp; Songwan',meta:'婚礼委托 / 2026.9 / iPad Procreate',lede:'为 Guci & Songwan 创作的一幅婚礼场景书法稿。',medium:'iPad Procreate',year:'2026.9',kind:'婚礼委托',story:['这幅字是为 Guci 和 Songwan 做的，想留给他们婚礼现场一个很柔软的瞬间，让空间慢慢变成只属于他们的空间。','我希望字像两条线相遇，绕着彼此走，但又保留各自的节奏。轻一点、庆祝一点，还有一点婚礼开始前大家努力忍住不哭的飘忽感。🥹','它用 Procreate 完成，是为了真正放进他们的婚礼场景里，不只是停在屏幕上。希望它能让那一天多一个停下来笑一笑的角落。🤍']});
Object.assign(modalLocales.ja.becoming,{title:'Guci &amp; Songwan',meta:'ウェディング依頼 / 2026.9 / iPad Procreate',lede:'Guci & Songwan のために、結婚式の空間へ届けるカリグラフィー。',medium:'iPad Procreate',year:'2026.9',kind:'ウェディング依頼',story:['これは Guci と Songwan のために制作した作品です。結婚式の空間が、少しずつ二人だけの場所になっていく、そのやわらかな瞬間に寄り添えたらと思いました。','二つの線が出会い、互いの周りを巡りながらも、それぞれのリズムを失わないように。やわらかく、祝福に満ちていて、みんなが泣かないようにがんばっている式の直前みたいな、少し浮遊感のある文字を目指しました。🥹','Procreate で制作し、画面の中だけでなく結婚式の風景の一部になるように仕立てました。その日に、少し立ち止まって笑える場所がひとつ増えたらうれしいです。🤍']});
modalLocales.zh.garden={title:'花园<br /><em>字母</em>',meta:'私人作品 / 2026.8 / iPad Procreate',lede:'一组让字母和植物慢慢同行的实验。',medium:'iPad Procreate',year:'2026.8',kind:'私人作品',story:['这是 garden lettering 字母实验的又一小段：让字母和植物共用一条线，然后慢慢、慢慢地缠在一起。','这次画了新的花卉，让它们以几乎有点不讲道理的慢速度绕着字母生长。不着急，藤蔓有自己的日历。🌿','它用 Procreate 制作，是一次让字母变成植物可以生长的地方的尝试。给字母表的一次小小花园绕路。🌼']};
modalLocales.ja.garden={title:'ガーデン<br /><em>レタリング</em>',meta:'個人作品 / 2026.8 / iPad Procreate',lede:'文字と植物が、長くゆっくり散歩するようなアルファベットの実験。',medium:'iPad Procreate',year:'2026.8',kind:'個人作品',story:['これは garden lettering の実験の新しい小さな章です。文字と植物が同じ線を共有し、ゆっくり絡まり合っていきます。','今回は別の花を描いて、ほとんど気の遠くなるほどゆっくりと、アルファベットの周りを巻いてもらいました。急がない。蔓には蔓のカレンダーがあるから。🌿','Procreate で制作した、文字を何かが育つ場所にしてみるための習作です。アルファベットの小さな植物園への寄り道。🌼']};
const plainModalTitle=html=>{const probe=document.createElement('div');probe.innerHTML=html;return probe.textContent.trim()};
const applyModalLanguage=lang=>{const activeKey=modal?.classList.contains('is-open')?Object.keys(modalProjects).find(key=>plainModalTitle(modalProjects[key].title)===document.getElementById('modal-title').textContent.trim()):null;Object.keys(modalProjects).forEach(key=>Object.assign(modalProjects[key],modalProjectBase[key],modalLocales[lang]?.[key]||{}));if(activeKey)openModal(activeKey)};
document.querySelectorAll('.language').forEach(button=>button.addEventListener('click',()=>applyModalLanguage(button.dataset.lang)));

Object.assign(translations.en,{'about.body':'Hi, I’m Raven. I studied piano at a conservatory, but somewhere between scales and late-night practice, I fell hard for calligraphy. 🎹✒️ I’ve been making English letterforms since 2015, and I still chase the same thing I loved in music: a line with breath, rhythm, and a little room to surprise you.'});
Object.assign(translations.zh,{'about.body':'嗨，我是 Raven。大学读的是音乐学院钢琴专业，但在音阶和练琴的日子里，我还是一头栽进了书法。🎹✒️ 我从 2015 年开始写英文书法。现在依然在笔触里追逐音乐的感觉：有呼吸、有节奏，也留一点意外给你。'});
Object.assign(translations.ja,{'about.body':'こんにちは、Raven です。大学では音楽院でピアノを学んでいましたが、音階と夜の練習のあいだに、すっかりカリグラフィーに夢中になりました。🎹✒️ 2015 年から英字書道を書いています。今も音楽で好きだったものを線の中で追いかけています。呼吸、リズム、そして少しだけ予想外の余白です。'});

const stablePortraitPanel=document.querySelector('.statement');if(stablePortraitPanel){directionObserver.unobserve(stablePortraitPanel);chapterTextObserver.unobserve(stablePortraitPanel);}

if(stablePortraitPanel){const portraitCopyObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting||stablePortraitPanel.classList.contains('about-revealed'))return;stablePortraitPanel.classList.add('about-revealed');const title=stablePortraitPanel.querySelector('.kinetic-title');title.style.animation='none';void title.offsetWidth;title.style.animation='';const copy=stablePortraitPanel.querySelector('.typing-copy');typeText(copy);[...copy.children].forEach((char,index)=>{char.style.animationDelay=`${.62+index*.018}s`;});portraitCopyObserver.unobserve(stablePortraitPanel)}),{threshold:.34});portraitCopyObserver.observe(stablePortraitPanel)}
